---

# repository to upload files to (as defined in .pypirc)
# see https://docs.python.org/3.5/distutils/packageindex.html#the-pypirc-file
pypi_repository: 'pypi'

# commands to execute for testing
test_command:
    - py.test tests --doctest-modules hatchery --cov hatchery --cov-report=term-missing
    - flake8 hatchery

