language: python

matrix:
    include:
        -   os: linux
            python: 2.7
        -   os: linux
            python: 3.3
        -   os: linux
            python: 3.4
        -   os: linux
            python: 3.5
        -   os: linux
            python: pypy
        -   os: osx
            python: 3.5

install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - hatchery clean test

after_success:
    - coveralls
