os:
    - linux
    - osx

language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - hatchery clean test

after_success:
    - coveralls
